name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
          python-version: 3.9.12

    - name: Run with setup-python 3.9
      run: |
        python -V
        python sender.py
